"""
User settings, authentication, and preferences API routes.

This module bundles several logical groups of endpoints on a single FastAPI
router (``/api/settings``) for simplicity, even though they cover distinct
domains:

  **Auth** (``/api/auth/*``)
    - POST   /auth/login             — Login with username & password.
    - POST   /auth/create-user       — Create additional user (multi-user mode).
    - GET    /auth/is-admin          — Check if current user is admin (id=1).
    - GET    /auth/has-user          — Check if any admin exists (always True).
    - GET    /auth/multi-user-mode   — Get whether multi-user is enabled.
    - GET    /auth/show-welcome      — Whether login page should be shown.
    - PUT    /auth/multi-user-mode   — Enable/disable multi-user (admin only).
    - GET    /auth/auto-login        — Auto-login as admin (single-user mode).

  **Settings** (``/api/settings/*``)
    - GET    /settings/user          — Get current username.
    - PUT    /settings/username      — Update username.
    - PUT    /settings/password      — Change password.
    - GET    /settings/visibility    — Get page & column visibility config.
    - PUT    /settings/visibility    — Save page & column visibility.

  **Currency** (``/api/currency/*``)
    - GET    /currency/thresholds    — Get currency thresholds.
    - PUT    /currency/thresholds    — Save currency thresholds.

All protected endpoints require ``Authorization: Bearer <token>``.
"""

import hashlib
import os
import secrets
from fastapi import APIRouter, HTTPException, Header, Body
from pydantic import BaseModel, Field

from app.database import get_connection

router = APIRouter()


# ═══════════════════════════════════════════════
# Password Hashing Helpers
# ═══════════════════════════════════════════════

def _hash_password(password: str) -> str:
    """Hash a password using SHA-256 with a random 32-byte salt.

    Format: ``<salt_hex>:<sha256_hex>``
    The salt is stored alongside the hash so we can verify later.
    This is **not** a production-grade password hashing scheme (use bcrypt
    or argon2 for that), but it provides basic protection for a self-hosted
    personal logbook where the threat model is casual access.
    """
    salt = os.urandom(32)
    pwd = salt + password.encode("utf-8")
    hashed = hashlib.sha256(pwd).hexdigest()
    return salt.hex() + ":" + hashed


def _verify_password(password: str, stored: str) -> bool:
    """Verify a plaintext password against a stored ``salt:hash`` string."""
    try:
        salt_hex, hashed = stored.split(":", 1)
        salt = bytes.fromhex(salt_hex)
        pwd = salt + password.encode("utf-8")
        return hashlib.sha256(pwd).hexdigest() == hashed
    except (ValueError, AttributeError):
        return False


# ═══════════════════════════════════════════════
# Session helpers (shared with flights router)
# ═══════════════════════════════════════════════

def _get_user_id(authorization: str) -> int:
    """Extract the authenticated user's ID from the Authorization header.

    Identical to the version in ``flights.py``; duplicated here to avoid
    a circular import. Looks up the Bearer token in the ``sessions`` table.
    """
    if not authorization:
        raise HTTPException(status_code=401, detail="Authorization required")
    token = authorization.replace("Bearer ", "").strip()
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT user_id FROM sessions WHERE token = ?", (token,)
        ).fetchone()
        if not row:
            raise HTTPException(status_code=401, detail="Invalid or expired token")
        return row["user_id"]
    finally:
        conn.close()


def _create_session(user_id: int, conn=None) -> str:
    """Create a session token for the given user ID.

    If an existing connection is provided (e.g. from the caller's
    ``with get_connection()`` block), we reuse it so that the token
    creation can be part of a larger transaction. Otherwise we create
    our own connection.

    The token itself is a cryptographically random 64-character hex
    string generated by ``secrets.token_hex(32)``.
    """
    token = secrets.token_hex(32)
    if conn is not None:
        conn.execute(
            "INSERT OR REPLACE INTO sessions (token, user_id) VALUES (?, ?)",
            (token, user_id),
        )
    else:
        own_conn = get_connection()
        try:
            own_conn.execute(
                "INSERT OR REPLACE INTO sessions (token, user_id) VALUES (?, ?)",
                (token, user_id),
            )
            own_conn.commit()
        finally:
            own_conn.close()
    return token


# ═══════════════════════════════════════════════
# Pydantic schemas (local to this module)
# ═══════════════════════════════════════════════

class UsernameUpdate(BaseModel):
    """Request body for PUT /settings/username."""
    username: str


class PasswordUpdate(BaseModel):
    """Request body for PUT /settings/password."""
    current_password: str
    new_password: str


class RegisterRequest(BaseModel):
    """Request body for POST /auth/create-user."""
    username: str
    password: str


class LoginRequest(BaseModel):
    """Request body for POST /auth/login."""
    username: str
    password: str


class MultiUserModeRequest(BaseModel):
    """Request body for PUT /auth/multi-user-mode."""
    enabled: bool
    password: str | None = None


class SetAdminPasswordRequest(BaseModel):
    """Request body for directly setting the admin password."""
    password: str
    current_password: str | None = None


class TokenResponse(BaseModel):
    """Response body for login and auto-login."""
    token: str
    username: str


class CurrencyThresholdEntry(BaseModel):
    """A single currency threshold entry (part of a batch save)."""
    category_id: str
    min_count: int = Field(ge=1)
    days_window: int = Field(ge=1)


class CurrencyThresholdsSaveRequest(BaseModel):
    """Request body for PUT /currency/thresholds."""
    thresholds: list[CurrencyThresholdEntry]


class VisibilitySaveRequest(BaseModel):
    """Request body for PUT /settings/visibility."""
    page_visibility: str  # JSON-encoded dict
    column_visibility: str  # JSON-encoded dict


# ── Auth endpoints ──


@router.post("/auth/login", response_model=TokenResponse)
async def login(data: LoginRequest):
    """Authenticate a user and return a session token.

    Verifies the username and password against the ``users`` table.
    Returns a session token that must be passed as ``Authorization: Bearer <token>``
    on subsequent requests.
    """
    if not data.username.strip():
        raise HTTPException(status_code=400, detail="Username and password are required")
    if not data.password:
        raise HTTPException(status_code=400, detail="Username and password are required")

    conn = get_connection()
    try:
        user_row = conn.execute(
            "SELECT id, username, password FROM users WHERE username = ?",
            (data.username.strip(),),
        ).fetchone()

        if not user_row:
            raise HTTPException(status_code=403, detail="Invalid username or password")

        if not _verify_password(data.password, user_row["password"]):
            raise HTTPException(status_code=403, detail="Invalid username or password")

        token = _create_session(user_row["id"], conn=conn)
        conn.commit()
        return {"token": token, "username": user_row["username"]}
    finally:
        conn.close()


@router.post("/auth/create-user", response_model=TokenResponse)
async def create_user(data: RegisterRequest):
    """Create an additional (non-admin) user.

    This endpoint is only intended for use in multi-user mode.
    It has no admin check because the first "create user" experience
    happens right after enabling multi-user, before there are any
    other users with credentials.
    """
    if not data.username.strip():
        raise HTTPException(status_code=400, detail="Username cannot be empty")
    if len(data.password) < 6:
        raise HTTPException(status_code=400, detail="Password must be at least 6 characters")

    conn = get_connection()
    try:
        dup = conn.execute(
            "SELECT id FROM users WHERE username = ?", (data.username.strip(),)
        ).fetchone()
        if dup:
            raise HTTPException(status_code=409, detail="Username already taken")

        cursor = conn.execute(
            "INSERT INTO users (username, password) VALUES (?, ?)",
            (data.username.strip(), _hash_password(data.password)),
        )
        user_id = cursor.lastrowid

        token = _create_session(user_id, conn=conn)
        conn.commit()
        return {"token": token, "username": data.username.strip()}
    finally:
        conn.close()


@router.get("/auth/is-admin")
async def is_admin(authorization: str = Header(None)):
    """Check if the currently authenticated user is the admin (user id = 1).

    Admin status is determined solely by user ID — the first user created
    by the system is always user 1, and there is no mechanism to change this.
    """
    try:
        user_id = _get_user_id(authorization)
    except HTTPException:
        return {"isAdmin": False}

    return {"isAdmin": user_id == 1}


@router.get("/auth/has-user")
async def has_user():
    """Check if any admin user exists.

    Since the admin user (id=1) is auto-created on first run by
    ``init_db()``, this always returns ``{hasUser: true}``.
    """
    return {"hasUser": True}


@router.get("/auth/multi-user-mode")
async def get_multi_user_mode():
    """Get whether multi-user mode is currently enabled.

    When disabled (default), the app auto-logs in as admin and skips
    the login page. When enabled, a login page is displayed and users
    must authenticate with a username and password.
    """
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT value FROM settings WHERE key = 'multi_user_mode'"
        ).fetchone()
        return {"multiUserMode": row is not None and row["value"] == "true"}
    finally:
        conn.close()


@router.get("/auth/show-welcome")
async def get_show_welcome():
    """Get whether the login page should be shown.

    Mirrors the multi_user_mode setting. The frontend uses this to
    decide whether to show the login page or auto-navigate straight
    to the dashboard.
    """
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT value FROM settings WHERE key = 'multi_user_mode'"
        ).fetchone()
        show = row is not None and row["value"] == "true"
        return {"showLoginPage": show}
    finally:
        conn.close()


@router.put("/auth/multi-user-mode")
async def set_multi_user_mode(data: MultiUserModeRequest, authorization: str = Header(None)):
    """Enable or disable multi-user mode (admin only).

    **Enabling**: Requires admin authentication. The provided password
    is either used to verify the existing admin password, or set as the
    initial admin password if none was set before.

    **Disabling**: Requires admin auth + current admin password verification.
    """
    user_id = _get_user_id(authorization)
    if user_id != 1:
        raise HTTPException(status_code=403, detail="Only admin can change multi-user mode")

    conn = get_connection()
    try:
        if data.enabled:
            if not data.password:
                raise HTTPException(status_code=400, detail="Password is required to enable multi-user mode")
            if len(data.password) < 6:
                raise HTTPException(status_code=400, detail="Password must be at least 6 characters")

            admin_row = conn.execute(
                "SELECT password FROM users WHERE id = 1"
            ).fetchone()

            if admin_row and admin_row["password"]:
                # Admin already has a password — verify current password
                if not _verify_password(data.password, admin_row["password"]):
                    raise HTTPException(status_code=403, detail="Incorrect password")
            else:
                # First time — set the password
                conn.execute(
                    "UPDATE users SET password = ? WHERE id = 1",
                    (_hash_password(data.password),),
                )
                conn.execute(
                    "INSERT OR REPLACE INTO settings (key, value) VALUES ('password_hash', ?)",
                    (_hash_password(data.password),),
                )

            conn.execute(
                "INSERT OR REPLACE INTO settings (key, value) VALUES ('multi_user_mode', 'true')",
            )
            conn.commit()
            return {"multiUserMode": True}
        else:
            if not data.password:
                raise HTTPException(status_code=400, detail="Password is required to disable multi-user mode")

            admin_row = conn.execute(
                "SELECT password FROM users WHERE id = 1"
            ).fetchone()
            if admin_row and admin_row["password"]:
                if not _verify_password(data.password, admin_row["password"]):
                    raise HTTPException(status_code=403, detail="Incorrect password")

            conn.execute(
                "INSERT OR REPLACE INTO settings (key, value) VALUES ('multi_user_mode', 'false')",
            )
            conn.commit()
            return {"multiUserMode": False}
    finally:
        conn.close()


@router.get("/auth/auto-login")
async def auto_login():
    """Auto-login as the admin user (only works when multi-user mode is disabled).

    When multi-user mode is off, there is no login page — the frontend
    calls this on mount to get a session token for the admin user (id=1).
    If no session exists, one is created. If multi-user mode is on, this
    endpoint returns a 403 and the frontend must show the login form instead.
    """
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT value FROM settings WHERE key = 'multi_user_mode'"
        ).fetchone()
        if row and row["value"] == "true":
            raise HTTPException(status_code=403, detail="Multi-user mode is enabled, use login instead")

        user_row = conn.execute(
            "SELECT id, username FROM users WHERE id = 1"
        ).fetchone()
        if not user_row:
            raise HTTPException(status_code=500, detail="Admin user not found")

        token = _create_session(user_row["id"], conn=conn)
        conn.commit()
        return {"token": token, "username": user_row["username"]}
    finally:
        conn.close()


# ── Settings endpoints ──


@router.get("/settings/user")
async def get_user(authorization: str = Header(None)):
    """Get the username of the currently authenticated user."""
    user_id = _get_user_id(authorization)
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT username FROM users WHERE id = ?", (user_id,)
        ).fetchone()
        return {"username": row["username"] if row else "pilot"}
    finally:
        conn.close()


@router.put("/settings/username")
async def update_username(data: UsernameUpdate, authorization: str = Header(None)):
    """Update the username for the authenticated user."""
    user_id = _get_user_id(authorization)
    if not data.username.strip():
        raise HTTPException(status_code=400, detail="Username cannot be empty")
    if len(data.username) > 100:
        raise HTTPException(status_code=400, detail="Username too long")

    conn = get_connection()
    try:
        conn.execute(
            "UPDATE users SET username = ? WHERE id = ?",
            (data.username.strip(), user_id),
        )
        conn.execute(
            "INSERT OR REPLACE INTO settings (key, value) VALUES ('username', ?)",
            (data.username.strip(),),
        )
        conn.commit()
        return {"username": data.username.strip()}
    finally:
        conn.close()


@router.put("/settings/password")
async def change_password(data: PasswordUpdate, authorization: str = Header(None)):
    """Change the password for the authenticated user.

    Requires the current password for verification. The new password
    must be at least 6 characters long.
    """
    user_id = _get_user_id(authorization)
    if len(data.new_password) < 6:
        raise HTTPException(status_code=400, detail="Password must be at least 6 characters")

    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT password FROM users WHERE id = ?", (user_id,)
        ).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="User not found")
        if not _verify_password(data.current_password, row["password"]):
            raise HTTPException(status_code=403, detail="Current password is incorrect")

        conn.execute(
            "UPDATE users SET password = ? WHERE id = ?",
            (_hash_password(data.new_password), user_id),
        )
        conn.execute(
            "INSERT OR REPLACE INTO settings (key, value) VALUES ('password_hash', ?)",
            (_hash_password(data.new_password),),
        )
        conn.commit()
        return {"status": "ok"}
    finally:
        conn.close()


# ── Currency endpoints ──


@router.get("/currency/thresholds")
async def get_currency_thresholds(authorization: str = Header(None)):
    """Get currency thresholds for the authenticated user.

    Thresholds define the minimum number of events (e.g. landings,
    instrument approaches) required within a rolling time window
    to maintain currency in each category.

    Returns a dict keyed by ``category_id`` with ``minCount`` and
    ``daysWindow`` values.
    """
    user_id = _get_user_id(authorization)
    conn = get_connection()
    try:
        rows = conn.execute(
            "SELECT category_id, min_count, days_window FROM currency_thresholds WHERE user_id = ?",
            (user_id,),
        ).fetchall()
        thresholds: dict[str, dict[str, int]] = {}
        for row in rows:
            thresholds[row["category_id"]] = {
                "minCount": row["min_count"],
                "daysWindow": row["days_window"],
            }
        return {"thresholds": thresholds}
    finally:
        conn.close()


@router.put("/currency/thresholds")
async def save_currency_thresholds(
    data: CurrencyThresholdsSaveRequest,
    authorization: str = Header(None),
):
    """Save currency thresholds for the authenticated user.

    Uses ``INSERT OR REPLACE`` so that calling this endpoint multiple
    times is idempotent. Sending an empty list clears all thresholds.
    """
    user_id = _get_user_id(authorization)
    conn = get_connection()
    try:
        for entry in data.thresholds:
            conn.execute(
                """INSERT OR REPLACE INTO currency_thresholds
                   (user_id, category_id, min_count, days_window)
                   VALUES (?, ?, ?, ?)""",
                (user_id, entry.category_id, entry.min_count, entry.days_window),
            )
        conn.commit()
        return {"status": "ok"}
    finally:
        conn.close()


# ── Visibility endpoints ──


@router.get("/settings/visibility")
async def get_visibility(authorization: str = Header(None)):
    """Get the page and column visibility configuration for the authenticated user.

    Visibility settings control which optional pages appear in the
    navigation bar and which columns appear in the Logbook and EntryForm.
    Both values are stored as JSON-encoded strings.
    """
    user_id = _get_user_id(authorization)
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT page_visibility, column_visibility FROM user_visibility WHERE user_id = ?",
            (user_id,),
        ).fetchone()
        if row:
            return {
                "pageVisibility": row["page_visibility"],
                "columnVisibility": row["column_visibility"],
            }
        return {"pageVisibility": "{}", "columnVisibility": "{}"}
    finally:
        conn.close()


@router.put("/settings/visibility")
async def save_visibility(
    data: VisibilitySaveRequest,
    authorization: str = Header(None),
):
    """Save the page and column visibility configuration for the authenticated user."""
    user_id = _get_user_id(authorization)
    conn = get_connection()
    try:
        conn.execute(
            """INSERT OR REPLACE INTO user_visibility
               (user_id, page_visibility, column_visibility)
               VALUES (?, ?, ?)""",
            (user_id, data.page_visibility, data.column_visibility),
        )
        conn.commit()
        return {"status": "ok"}
    finally:
        conn.close()
